version: "3.8"
services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: